### ISSUE TITLE
error using the CLI

### ISSUE THREAD

**Issue by teikjoon** [sbrunner/deskew#13]
Hello,

Trying to run deskew from command line, I get this error -

```
Traceback (most recent call last):
  File "/usr/local/bin/deskew", line 7, in <module>
    from deskew.cli import main
  File "/usr/local/lib/python2.7/dist-packages/deskew/__init__.py", line 8
    def _get_max_freq_elem(peaks: List[int]) -> List[float]:
                                ^
SyntaxError: invalid syntax

```

**Comment by sbrunner** [comment]
You probably use a Python version older than 3.5...
